### ISSUE TITLE
No notification when messages are dropped due to budget

### ISSUE THREAD

**Issue by ace13** [networkprotocol/libyojimbo#42] opened 2017-03-26 21:25 UTC
Currently, if you try to send a message with a size that happens to exceed the packet budget on it's channel, then the message itself will be silently dropped after failing to fit into a packet.
This is impossible to see from the applications point of view, as no counters are affected, no error state is set, and the packet itself sends correctly - albeit without the oversized message.

Some kind of notification when this happens would be appreciated, instead of the oversized message silently disappearing into the ether.

**Comment by gafferongames** [comment] 2017-03-27 19:18
Which channel type are you sending the message over? Is it the unreliable channel?

I'd be happy to add a debug build only warning, to help people get indication that stuff is being lost due to budget.

Would that be acceptable?

**Comment by ace13** [comment] 2017-03-27 19:22
In this case, the message was over a reliable channel. And it only exceeded the budget due to a run-time reason (String being embedded in the message was of larger than expected size).

Could it be possible to add a counter for messages dropped due to being over budget at least?
Something that can be checked at runtime, to at least let the application give the user some kind of notification that their packets aren't being sent.

**Comment by gafferongames** [comment] 2017-03-28 03:24
I don't think you actually need something to be checked at runtime, because in the case of a reliable-ordered channel, you can never actually recover. If you send a message to large to fit in budget your channel will be broken from that point forward. I think it should be an assert/warning at most. 

In other words, the real solution is to increase your budget, right?

**Comment by ace13** [comment] 2017-03-28 04:56
Indeed the solution would be to increase the budget, something I'd like to
be able to communicate to the user in question, so their game doesn't just
suddenly - silently - stop doing networking properly.

I guess you could set an error flag if this was to happen? That way I can
generate an error that actually tells the user that something's gone wrong.

**Comment by gafferongames** [comment] 2017-03-28 17:56
Help me understand your situation, it sounds like you are creating a library rather than an application?

**Comment by ace13** [comment] 2017-03-28 18:07
So, I have an application where the size of one message depends heavily on how the client has installed the application in question. In certain cases it might even end up large enough that it overflows the default budget of the channel.

Currently, when that message is sent the whole networking system just suddenly - silently - begins acting strangely, especially since only the reliable messages are affected.

I'd really like to have some way to detect if this was to happen, instead of just leaving the user with a completely broken experience that still believes it's working properly.

**Comment by gafferongames** [comment] 2017-03-28 22:35
I'm torn on this one. 

It's a reliable-ordered channel, so no matter what, I really can't just drop that message and carry on like nothing has happened, arguably that's worse than actually failing like it currently does.

What I suggest is a fatal error which will disconnect the client, ultimately sending a message larger than budget through channels should be a fatal error.

I have a mechanism for such a fatal error already, and it should work fine. 

I'll look into this today. If I can add a counter as well, then bonus.

**Comment by gafferongames** [comment] 2017-03-28 22:39
Similarly, sending a message through that is larger than the channel should be a fatal error for the unreliable channel too, for consistency, but also because because it's ultimately a user error and the user should configure the channel size properly to avoid this (and the user should be made aware that it is misconfigured instead of failing silently).

**Comment by gafferongames** [comment] 2017-03-28 22:39
Will this solve your issue?

**Comment by ace13** [comment] 2017-03-29 04:42
An error and a dropped connection sounds like it'd work quite well, especially if an error flag or counter is set so I can communicate the reason for the disconnect to the user.

**Comment by gafferongames** [comment] 2017-03-29 15:11
I forgot to ask, but is the bad message being sent from client -> server, or server -> client?

**Comment by ace13** [comment] 2017-03-29 15:27
Client -> Server

Which is part of the reason why it took me many hours to figure out what was going on, and part of why I really want this outside of debug builds.

**Comment by gafferongames** [comment] 2017-03-30 16:51
Understood. The reason I'm asking is that there is currently no good way to flag errors if it is the other way right now, eg. server -> client, since that client slot gets completely cleared on error. That's all.

I'll sort this out this weekend for you. 

cheers

- Glenn

**Comment by gafferongames** [comment] 2017-04-03 02:51
I'm thinking now of doing something else. If a message is larger than half the budget, serialize it automatically as a block, so it will always work. What do you think about this?

**Comment by gafferongames** [comment] 2017-04-03 02:51
(this would only be for reliable channel, unreliable channel would have same behavior, perhaps with a counter for # of messages dropped because too large)

**Comment by gafferongames** [comment] 2017-04-03 03:09
As a workaround to unblock you, I recommend putting this problematic (dynamic sized) block of data inside a message block and sending it over the reliable channel. This was designed to handle situations where the message size exceeds the channel budget, eg. large blocks on connect.

**Comment by ace13** [comment] 2017-04-03 12:16
Well, block messages seem designed to do this, so it sounds like a reasonable solution.

**Comment by gafferongames** [comment] 2017-04-03 16:55
Yes, but I agree that the silent failure when they're not used is bad, so I'll still work out something to solve that. I'm glad you are unblocked. Let me know how it goes -- cheers

**Comment by gafferongames** [comment] 2017-04-08 21:19
Closing this out because user is unblocked, I'll add better error reporting for this situation in the future.

**Closed by gafferongames** 2017-04-08 21:19 UTC

**Comment by ace13** [comment] 2017-04-08 22:08
Can add that my current solution ended up implemented much like your thought for solving it; messages larger than 50% of the packet budget will be automatically packed into block messages.
Even threw automated zlib deflation on them if they fall within certain size ranges.

If people are curious about how to do this themselves, I stripped out some implementation-specific details and put the server part of it up as a gist;
https://gist.github.com/ace13/5e0a54e444bf26445ad60d39952d7a31

**Comment by gafferongames** [comment] 2017-04-08 23:54
Very nice. Thanks for sharing!

**Comment by gafferongames** [comment] 2017-04-08 23:56
Oh I have something to add that will improve your code, you can use a MeasureStream, it's specifically designed for the case where you want to know how many bits something will serialize to, and it doesn't require the allocation of a buffer. -- cheers

**Comment by gafferongames** [comment] 2017-04-08 23:57
Oh but I see you want to actually serialize to a buffer,  because if it's large you turn that into a block. Never mind :)
