### ISSUE TITLE
Cmake?

### ISSUE THREAD

**Issue by fire** [networkprotocol/libyojimbo#21] opened 2016-11-19 18:43 UTC
Would you accept a cmake version of the build system? If I made one? Not sure how to deal with two versions of the build system though because one be outdated.

**Comment by gafferongames** [comment] 2016-11-22 00:04
Thanks for the offer. What do you propose? Would the CMake just trail behind a bit? Are you volunteering to maintain the CMake build system on all platforms?

**Comment by fire** [comment] 2016-11-22 10:19
Let me get a prototype cmake project running then and see.

**Comment by fire** [comment] 2016-11-22 11:38
Here is an initial [cmake for Windows](https://github.com/fire/libyojimbo/tree/cmake). The various executables compile but secure_server didn't run.

Todo: 

* Build libsodium and mbedtls through https://github.com/ruslo/hunter
* Linux support
* Docker startup
* cppcheck
* scan-build
* coverity
* loc
* release
* sublime
* stress

**Comment by fire** [comment] 2016-11-22 11:45
Prefixed the executables with yojimbo because the test is a reserved project name.

**Comment by gafferongames** [comment] 2016-11-26 06:33
No need to port:

- cppcheck
- scan-build
- coverity (doesn't work...)
- loc (just counts lines of code)
- release (i'll stick with premake for this)
- sublime (just generates a sublime text project on demand so I don't need to check it in)

Basically, I don't think it's necessary to port any of the "shortcuts" actions I've setup in premake to CMake. If you build a CMake version that works on Windows, Linux, MacOSX that's would be fine.

Also, nice benefit for CMake is automatic install for libsodium and mbedtls, vs. premake5 being a manual install, as well as on Linux, the install of mbedtls/libsodium can be a bit painful on Debian.

cheers

- Glenn

**Comment by gafferongames** [comment] 2016-11-26 06:35
Can you give more detail about secure_server? Why does it not run? It's important that works. Does secure_server run on your machine when you build it with premake instead?

**Comment by fire** [comment] 2016-11-26 15:17
`secure server started on port 40000` but I don't know how to secure connect.

**Comment by fire** [comment] 2016-11-26 15:34
YOJIMBO_INSECURE_CONNECT does not compile when set to 0.

**Comment by fire** [comment] 2016-11-26 15:38
Also I would like some sort of `YOJIMBO_SECURE_CONNECT_ONLY` that does not require me to force remove a definition. 

For instance if I want to enable secure connections. All I want is to enable one flag.

```cmake
add_executable(
  yojimbo_client
  yojimbo
  tests/client.cpp
  )

target_compile_definitions(  yojimbo_client PRIVATE SECURE_CLIENT=1)

target_link_libraries(
  yojimbo_client
  yojimbo
  )
```

**Comment by gafferongames** [comment] 2016-11-27 22:49
Oh the secure connect is working fine. It's by design that the regular client cannot connect to the server, as it only allows secure connects through the matcher (eg. "premake5 matcher" followed by "premake5 connect").

cheers

**Comment by gafferongames** [comment] 2016-11-27 22:50
I'll think about the YOJIMBO_SECURE_CONNECT_ONLY idea, give me second, I'm poking around the source right now.

**Comment by gafferongames** [comment] 2016-11-27 23:27
Replaced YOJIMBO_ALLOW_INSECURE_CONNECT with YOJIMBO_SECURE_MODE, and fixed the compile errors. https://github.com/networkprotocol/libyojimbo/commit/7e79844cfc229f054fdf7ee12263f3218fc281f3

**Comment by fire** [comment] 2016-11-28 01:24
Looks good. However the yojimbo secure client doesn't automatically connect to the server anymore. Not sure the details, but the code is empty.

**Comment by gafferongames** [comment] 2016-11-28 01:37
Hmmmm. Let me double check

**Comment by gafferongames** [comment] 2016-11-28 01:38
Oh, "connect.cpp" was moved to "secure_client.cpp" so it's more obvious how to secure connect a client.

Also, I just make a check-in that split apart "secure_server.cpp" from "server.cpp", because that code was getting hard to read, and it's consistent. eg. client -> server, secure_client.cpp -> secure_server.

cheers

**Comment by gafferongames** [comment] 2016-11-28 19:23
I'm closing this issue as it seems you should be unblocked. Let me know when you have a pull request, I'm happy to review it. 

cheers

- Glenn

**Closed by gafferongames** 2016-11-28 19:23 UTC

**Comment by fire** [comment] 2016-12-10 08:16
I found some time to work on this.

**Comment by fire** [comment] 2016-12-10 09:29
The cmake project now have sodium integrated with hunter. Just waiting on the other package.

**Comment by gafferongames** [comment] 2016-12-16 02:58
Thanks!
